"""empty message

Revision ID: 87075fa77647
Revises: 2807edd385a2
Create Date: 2022-02-23 20:31:11.816906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87075fa77647'
down_revision = '2807edd385a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=1000),
               existing_nullable=False)
    op.alter_column('user', 'password',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=1000),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'password',
               existing_type=sa.String(length=1000),
               type_=sa.VARCHAR(length=80),
               existing_nullable=False)
    op.alter_column('user', 'email',
               existing_type=sa.String(length=1000),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)
    # ### end Alembic commands ###
